version: '3.8'
services:
  app_db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: artur
      PGDATA: /data/postgres
      DATABASE: meally
      DATABASE_TESTS: meally_tests
    volumes:
      - ./packages/app/scripts/db:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    restart: unless-stopped
  app:
    build:
      dockerfile: Dockerfile.dev
      context: "./packages/app"
    volumes:
      - /app/node_modules
      - ./app:/app
    environment:
      - PGUSER=artur
      - PGHOST=postgres
      - PGDATABASE=meally
      - PGPASSWORD=postgres_password
      - PGPORT=5432


